@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US001 Sequence Diagram (SD)

autonumber

actor "Unregistered User" as UnregisteredUser
participant ":PropertiesListUI" as UI
participant ":PropertiesListController" as CTRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as RepRep
participant "AdvertisementRepository\n:AdvertisementRepository" as AdvertisementRepository
participant "Filtering" as filter
participant "Sorting" as sorter

activate UnregisteredUser


UnregisteredUser -> UI : Request properties list
activate UI

UI -> CTRL** : create

UI -> CTRL : getAdvertisements()
activate CTRL

CTRL -> REP : getInstance()
activate REP

REP --> CTRL: repositories
deactivate REP

CTRL -> RepRep : getAdvertisementRepository()
activate RepRep

RepRep --> CTRL: AdvertisementRepository
deactivate RepRep

CTRL -> AdvertisementRepository : getAdvertisements()
activate AdvertisementRepository

AdvertisementRepository --> CTRL : Advertisement
deactivate AdvertisementRepository

CTRL --> UI : PropertiesList
deactivate CTRL

UI --> UnregisteredUser : Return list sorted by latest listings and asks if it wishes to filter the list (yes,no)
deactivate UI

UnregisteredUser -> UI : Unregistered User responds
opt UnregisteredUser User wants to filter results
activate UI

UI --> UnregisteredUser : Ask if it wants to choose between for sale properties and renting properties (yes,no)
deactivate UI

UnregisteredUser -> UI : Unregistered User responds
activate UI
opt User wants to choose type of business
UI --> UnregisteredUser : Ask to choose between rented or for sale properties (r,s)
deactivate UI
UnregisteredUser -> UI : Unregistered User responds
activate UI


ref over CTRL
c.f. Filter Example
end ref
UI -> CTRL : getFilteredByRequestTypeList(filteredList, requestType)
activate CTRL


CTRL -> filter : filterRequestType(list, request)
activate filter

filter --> CTRL: RequestTypeFilteredList
deactivate filter






deactivate AdvertisementRepository

CTRL --> UI : RequestTypeFilteredList
deactivate CTRL

UI --> UnregisteredUser : Categorizes properties for rent or sale, lists and sorts by newest, asks if user wants to choose the type of property (yes,no)
deactivate UI

UnregisteredUser -> UI : Unregistered User responds
activate UI


end


opt User wants to choose the type of property

UI --> UnregisteredUser : Ask to choose the type of property, land, house, apartment (l,h,a)
deactivate UI

UnregisteredUser -> UI : User responds
activate UI

UI -> CTRL : getFilteredByPropertyTypeList(filteredList, propertyType)
activate CTRL


CTRL -> filter : filterPropertyType(list, propertyType)
activate filter

filter --> CTRL: PropertyTypeFilteredList
deactivate filter

CTRL --> UI : PropertyAndRequestFilteredList
deactivate CTRL



UI --> UnregisteredUser : Lists chosen property type for sale or rent and sorts by newest, asks if it wants to choose the number of bedrooms (yes,no)
deactivate UI

UnregisteredUser -> UI : Unregistered User responds
activate UI



end



opt User wants to choose the number of bedrooms in the property

UI --> UnregisteredUser : Ask the number of bedrooms it wants (number)

deactivate UI

UnregisteredUser -> UI : Unregistered User responds
activate UI

end
UI -> CTRL : getFilteredByNumberBedroomsList(filteredList, numberBedrooms)
activate CTRL


CTRL -> filter : filterNumberOfRooms(list, numberBedrooms)
activate filter

filter --> CTRL: NumberOfRoomsFilteredList
deactivate filter

CTRL --> UI : FullyFilteredList
deactivate CTRL

deactivate CTRL

UI--> UnregisteredUser : Shows listed properties according to the filters and sorted by most recent and ask if it wishes to use a sorting method

deactivate UI
end


UnregisteredUser -> UI : Unregistered User responds
activate UI

opt User wants to use a sorting method

UI --> UnregisteredUser : Ask if it wants to sort the list by city, district or price (c,d,p)
deactivate UI

UnregisteredUser -> UI : Unregistered User responds
activate UI

UI -> CTRL : getSortedByXList(filteredList)
activate CTRL

CTRL -> sort : sortByX(list)
activate sort
sort -> CTRL : sortedByXList
deactivate sort

CTRL --> UI : FilteredAndSortedList
deactivate CTRL

UI --> UnregisteredUser : FilteredAndSortedList
deactivate UI
end

@enduml